CREATE TABLE IF NOT EXISTS trade_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  annual_plan_id BIGINT UNSIGNED NULL,
  office_id BIGINT UNSIGNED NOT NULL,
  directorate_id BIGINT UNSIGNED NULL,
  team_id BIGINT UNSIGNED NULL,
  fiscal_year VARCHAR(20) NOT NULL,
  month VARCHAR(40) NULL,
  period_type ENUM('annual','monthly') NOT NULL DEFAULT 'annual',
  commodity_group VARCHAR(191) NOT NULL,
  commodity VARCHAR(191) NOT NULL,
  stage VARCHAR(191) NOT NULL DEFAULT 'Value Chain',
  unit VARCHAR(80) NOT NULL DEFAULT 'Qt',
  plan_product DECIMAL(18,2) NOT NULL DEFAULT 0,
  plan_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  plan_income DECIMAL(18,2) NOT NULL DEFAULT 0,
  achievement_product DECIMAL(18,2) NOT NULL DEFAULT 0,
  achievement_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  achievement_income DECIMAL(18,2) NOT NULL DEFAULT 0,
  employment_male_plan INT NOT NULL DEFAULT 0,
  employment_female_plan INT NOT NULL DEFAULT 0,
  employment_male_achievement INT NOT NULL DEFAULT 0,
  employment_female_achievement INT NOT NULL DEFAULT 0,
  status ENUM('draft','submitted','commented','approved','returned') NOT NULL DEFAULT 'submitted',
  review_comment TEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX trade_records_scope_index (office_id, directorate_id, team_id),
  INDEX trade_records_year_month_index (fiscal_year, month),
  INDEX trade_records_annual_plan_id_index (annual_plan_id),
  UNIQUE KEY trade_annual_unique (office_id, directorate_id, team_id, fiscal_year, commodity_group, commodity, period_type),
  UNIQUE KEY trade_month_unique (annual_plan_id, month),
  CONSTRAINT trade_records_office_fk FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT,
  CONSTRAINT trade_records_directorate_fk FOREIGN KEY (directorate_id) REFERENCES directorates(id) ON DELETE SET NULL,
  CONSTRAINT trade_records_team_fk FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL,
  CONSTRAINT trade_records_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT trade_records_approver_fk FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT trade_records_annual_fk FOREIGN KEY (annual_plan_id) REFERENCES trade_records(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trade_review_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trade_record_id BIGINT UNSIGNED NOT NULL,
  action ENUM('comment','approve','return','submit') NOT NULL,
  comment TEXT NULL,
  acted_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX trade_review_history_record_index (trade_record_id),
  CONSTRAINT trade_review_history_record_fk FOREIGN KEY (trade_record_id) REFERENCES trade_records(id) ON DELETE CASCADE,
  CONSTRAINT trade_review_history_actor_fk FOREIGN KEY (acted_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
