CREATE TABLE IF NOT EXISTS organization_access_mappings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  office_id BIGINT UNSIGNED NOT NULL,
  directorate_id BIGINT UNSIGNED NULL,
  team_id BIGINT UNSIGNED NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  module VARCHAR(80) NOT NULL,
  scope_type VARCHAR(80) NOT NULL DEFAULT 'all',
  scope_value VARCHAR(191) NULL,
  can_create_annual_plan TINYINT(1) NOT NULL DEFAULT 0,
  can_divide_monthly_plan TINYINT(1) NOT NULL DEFAULT 0,
  can_update_achievement TINYINT(1) NOT NULL DEFAULT 0,
  can_view_report TINYINT(1) NOT NULL DEFAULT 0,
  can_comment TINYINT(1) NOT NULL DEFAULT 0,
  can_approve TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_oam_office FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE CASCADE,
  CONSTRAINT fk_oam_directorate FOREIGN KEY (directorate_id) REFERENCES directorates(id) ON DELETE CASCADE,
  CONSTRAINT fk_oam_team FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  CONSTRAINT fk_oam_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  UNIQUE KEY uq_oam_scope (office_id, directorate_id, team_id, role_id, module, scope_type, scope_value),
  INDEX idx_oam_lookup (office_id, directorate_id, team_id, role_id, is_active),
  INDEX idx_oam_module_scope (module, scope_type, scope_value)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
