"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Edit, Loader2, MoreHorizontal, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
type Item={id:number;name:string;code?:string|null;is_active?:boolean|number;[key:string]:unknown}; type Parent={id:number;name:string;is_active?:boolean|number}; type Api<T>={success:boolean;message:string;data:T;meta?:{total?:number;last_page?:number;current_page?:number}};
type Props={title:string;description:string;endpoint:string;parentEndpoint:string;parentKey:"crop_type_id"|"crop_id";parentLabel:string;parentNameKey:"crop_type_name"|"crop_name";createLabel:string};
async function req<T>(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{Accept:"application/json","Content-Type":"application/json",...(options?.headers??{})}});const b=await r.json().catch(()=>null) as Api<T>|null;if(!r.ok||!b?.success)throw new Error(b?.message||"Request failed");return b}
export function CategoryCrudPage(p:Props){const [items,setItems]=useState<Item[]>([]),[parents,setParents]=useState<Parent[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[parentFilter,setParentFilter]=useState("all"),[page,setPage]=useState(1),[last,setLast]=useState(1),[total,setTotal]=useState(0),[open,setOpen]=useState(false),[del,setDel]=useState(false),[selected,setSelected]=useState<Item|null>(null),[parentId,setParentId]=useState(""),[name,setName]=useState(""),[active,setActive]=useState(true);
 const activeParents=useMemo(()=>parents.filter(x=>x.is_active===true||x.is_active===1),[parents]);
 async function loadParents(){try{setParents((await req<Parent[]>(`${p.parentEndpoint}?all=1&status=active`)).data)}catch(e){toast.error(e instanceof Error?e.message:"Failed to fetch parent data")}}
 async function load(n=page){setLoading(true);try{const q=new URLSearchParams({page:String(n),per_page:"10",search,status,[p.parentKey]:parentFilter});const x=await req<Item[]>(`${p.endpoint}?${q}`);setItems(x.data);setPage(n);setLast(Number(x.meta?.last_page??1));setTotal(Number(x.meta?.total??0))}catch(e){toast.error(e instanceof Error?e.message:"Failed to fetch categories")}finally{setLoading(false)}}
 useEffect(()=>{loadParents()},[]); useEffect(()=>{const t=setTimeout(()=>load(1),250);return()=>clearTimeout(t)},[search,status,parentFilter]);
 function create(){setSelected(null);setParentId("");setName("");setActive(true);setOpen(true)} function edit(x:Item){setSelected(x);setParentId(String(x[p.parentKey]??""));setName(x.name);setActive(x.is_active===true||x.is_active===1);setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();if(!parentId||!name.trim()){toast.error(`${p.parentLabel} and name are required`);return}setSaving(true);try{await req(selected?`${p.endpoint}/${selected.id}`:p.endpoint,{method:selected?"PUT":"POST",body:JSON.stringify({[p.parentKey]:Number(parentId),name:name.trim(),is_active:active})});toast.success(selected?"Category updated successfully":"Category created successfully");setOpen(false);await load(page)}catch(e){toast.error(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}}
 async function remove(){if(!selected)return;setSaving(true);try{await req(`${p.endpoint}/${selected.id}`,{method:"DELETE"});toast.success("Category deleted successfully");setDel(false);setSelected(null);await load(1)}catch(e){toast.error(e instanceof Error?e.message:"Delete failed")}finally{setSaving(false)}}
 return <div className="space-y-6 p-4 md:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">{p.title}</h1><p className="text-sm text-muted-foreground">{p.description}</p></div><Button onClick={create}><Plus className="mr-2 h-4 w-4"/>{p.createLabel}</Button></div>
 <div className="grid gap-3 md:grid-cols-[1fr_220px_180px_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={parentFilter} onValueChange={setParentFilter}><SelectTrigger><SelectValue placeholder={p.parentLabel}/></SelectTrigger><SelectContent><SelectItem value="all">All {p.parentLabel}s</SelectItem>{parents.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.name}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Statuses</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select><Button variant="outline" onClick={()=>load(page)}><RefreshCw className="h-4 w-4"/></Button></div>
 <div className="rounded-md border"><Table><TableHeader><TableRow><TableHead>{p.parentLabel}</TableHead><TableHead>Category</TableHead><TableHead>Code</TableHead><TableHead>Status</TableHead><TableHead className="w-16"/></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={5} className="h-28 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin"/></TableCell></TableRow>:items.length?items.map(x=><TableRow key={x.id}><TableCell>{String(x[p.parentNameKey]??"-")}</TableCell><TableCell className="font-medium">{x.name}</TableCell><TableCell>{x.code||"-"}</TableCell><TableCell><Badge variant={(x.is_active===true||x.is_active===1)?"default":"secondary"}>{(x.is_active===true||x.is_active===1)?"Active":"Inactive"}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>edit(x)}><Edit className="mr-2 h-4 w-4"/>Edit</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive" onClick={()=>{setSelected(x);setDel(true)}}><Trash2 className="mr-2 h-4 w-4"/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>):<TableRow><TableCell colSpan={5} className="h-28 text-center text-muted-foreground">No categories found.</TableCell></TableRow>}</TableBody></Table></div>
 <div className="flex items-center justify-between text-sm"><span className="text-muted-foreground">{total} record(s)</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page<=1||loading} onClick={()=>load(page-1)}>Previous</Button><span className="px-2 py-2">Page {page} of {last}</span><Button variant="outline" size="sm" disabled={page>=last||loading} onClick={()=>load(page+1)}>Next</Button></div></div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><form onSubmit={save}><DialogHeader><DialogTitle>{selected?"Edit":"Create"} Category</DialogTitle><DialogDescription>Maintain the category hierarchy without changing existing planning records.</DialogDescription></DialogHeader><div className="space-y-4 py-4"><div className="space-y-2"><Label>{p.parentLabel}</Label><Select value={parentId} onValueChange={setParentId}><SelectTrigger><SelectValue placeholder={`Select ${p.parentLabel.toLowerCase()}`}/></SelectTrigger><SelectContent>{activeParents.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Category Name</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter category name"/></div><div className="space-y-2"><Label>Status</Label><Select value={active?"active":"inactive"} onValueChange={v=>setActive(v==="active")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{selected?"Update":"Create"}</Button></DialogFooter></form></DialogContent></Dialog>
 <AlertDialog open={del} onOpenChange={setDel}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete category?</AlertDialogTitle><AlertDialogDescription>This action is blocked when the category is already in use.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={remove} disabled={saving}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>}
