"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Edit, Eye, Loader2, Search } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Api<T>={success:boolean;message:string;data:T};
type Row={id:number;name:string;code?:string|null;is_active?:boolean|number;crop_type_id?:number;crop_type_category_id?:number|null;crop_id?:number;crop_type_name?:string;crop_type_category_name?:string;crop_name?:string};
async function get<T>(url:string){const r=await fetch(url,{headers:{Accept:"application/json"}});const b=await r.json() as Api<T>;if(!r.ok||!b.success)throw new Error(b.message||"Request failed");return b.data}
const active=(v:unknown)=>v===true||v===1;
export default function CropCategoriesPage(){
 const [types,setTypes]=useState<Row[]>([]),[typeCats,setTypeCats]=useState<Row[]>([]),[crops,setCrops]=useState<Row[]>([]),[cats,setCats]=useState<Row[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[expanded,setExpanded]=useState<Set<string>>(new Set()),[kind,setKind]=useState("all"),[page,setPage]=useState(1),[perPage,setPerPage]=useState(10);
 useEffect(()=>{(async()=>{setLoading(true);try{const [a,b,c,d]=await Promise.all([get<Row[]>("/api/admin/crop-types?all=1"),get<Row[]>("/api/admin/crop-type-categories?all=1"),get<Row[]>("/api/admin/crops?all=1"),get<Row[]>("/api/admin/crop-categories?all=1")]);setTypes(a);setTypeCats(b);setCrops(c);setCats(d);setExpanded(new Set(a.map(x=>`t-${x.id}`)))}catch(e){toast.error(e instanceof Error?e.message:"Unable to load crop hierarchy")}finally{setLoading(false)}})()},[]);
 const rows=useMemo(()=>{const q=search.trim().toLowerCase(), out:Array<Row&{key:string;level:number;kind:string;parent:string}>=[];const ok=(x:Row)=>status==="all"||(status==="active"?active(x.is_active):!active(x.is_active)); for(const t of types){const tc=typeCats.filter(x=>x.crop_type_id===t.id), direct=crops.filter(x=>x.crop_type_id===t.id&&!x.crop_type_category_id);const children=[...tc,...direct];const match=!q||t.name.toLowerCase().includes(q)||children.some(x=>x.name.toLowerCase().includes(q));if(!match)continue;if(ok(t))out.push({...t,key:`t-${t.id}`,level:1,kind:"Crop Type",parent:"-"});if(expanded.has(`t-${t.id}`)||q){for(const c of tc){if(ok(c))out.push({...c,key:`tc-${c.id}`,level:2,kind:"Type Category",parent:t.name});const cc=crops.filter(x=>x.crop_type_category_id===c.id);for(const crop of cc){if(ok(crop))out.push({...crop,key:`c-${crop.id}`,level:3,kind:"Crop",parent:c.name});for(const sub of cats.filter(x=>x.crop_id===crop.id))if(ok(sub))out.push({...sub,key:`sc-${sub.id}`,level:4,kind:"Crop Category",parent:crop.name})}}for(const crop of direct){if(ok(crop))out.push({...crop,key:`c-${crop.id}`,level:2,kind:"Crop",parent:t.name});for(const sub of cats.filter(x=>x.crop_id===crop.id))if(ok(sub))out.push({...sub,key:`sc-${sub.id}`,level:3,kind:"Crop Category",parent:crop.name})}}}return out},[types,typeCats,crops,cats,search,status,expanded]);
 const filteredRows=useMemo(()=>kind==="all"?rows:rows.filter(r=>r.kind===kind),[rows,kind]);
 const totalPages=Math.max(1,Math.ceil(filteredRows.length/perPage));
 const currentPage=Math.min(page,totalPages);
 const paginatedRows=filteredRows.slice((currentPage-1)*perPage,currentPage*perPage);
 useEffect(()=>setPage(1),[search,status,kind,perPage]);
 const toggle=(key:string)=>setExpanded(s=>{const n=new Set(s);n.has(key)?n.delete(key):n.add(key);return n});
 const href=(kind:string)=>kind==="Crop Type"?"/dashboard/crop-types":kind==="Type Category"?"/dashboard/crop-type-categories":kind==="Crop"?"/dashboard/crops":"/dashboard/crop-categories";
 return <div className="p-1 md:p-2"> <div className="rounded-xl border bg-card p-4 shadow-sm"><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{[["all","All"],["Crop Type","Crop Types"],["Type Category","Type Categories"],["Crop","Crops"],["Crop Category","Crop Categories"]].map(([value,label])=><Button key={value} type="button" size="sm" variant={kind===value?"default":"outline"} onClick={()=>setKind(value)}>{label}</Button>)}</div><div className="flex gap-2"><div className="relative min-w-64"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} className="pl-9" placeholder="Search by name or code..."/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Status</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></div></div>
 <div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead className="w-16">#</TableHead><TableHead>Name</TableHead><TableHead>Code</TableHead><TableHead>Type</TableHead><TableHead>Parent</TableHead><TableHead>Level</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={8} className="h-40 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin"/></TableCell></TableRow>:paginatedRows.map((r,i)=><TableRow key={r.key}><TableCell>{(currentPage-1)*perPage+i+1}</TableCell><TableCell><div className="flex items-center" style={{paddingLeft:(r.level-1)*24}}>{r.kind==="Crop Type"?<button className="mr-2" onClick={()=>toggle(r.key)}>{expanded.has(r.key)?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button>:<span className="mr-2 w-4"/>}<span className="mr-2">{r.kind.includes("Crop")?"🌾":"🌱"}</span><span className="font-medium">{r.name}</span></div></TableCell><TableCell>{r.code||"-"}</TableCell><TableCell><Badge variant="secondary">{r.kind}</Badge></TableCell><TableCell>{r.parent}</TableCell><TableCell>Level {r.level}</TableCell><TableCell><Badge variant={active(r.is_active)?"default":"secondary"}>{active(r.is_active)?"Active":"Inactive"}</Badge></TableCell><TableCell><div className="flex justify-end gap-1"><Button asChild size="icon" variant="outline"><Link href={href(r.kind)}><Edit className="h-4 w-4"/></Link></Button><Button asChild size="icon" variant="ghost"><Link href={href(r.kind)}><Eye className="h-4 w-4"/></Link></Button></div></TableCell></TableRow>)}{!loading&&!filteredRows.length&&<TableRow><TableCell colSpan={8} className="h-32 text-center text-muted-foreground">No crop hierarchy records found.</TableCell></TableRow>}</TableBody></Table></div><div className="mt-4 flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3 text-sm text-muted-foreground"><span>Showing {filteredRows.length?((currentPage-1)*perPage)+1:0}–{Math.min(currentPage*perPage,filteredRows.length)} of {filteredRows.length}</span><Select value={String(perPage)} onValueChange={v=>setPerPage(Number(v))}><SelectTrigger className="h-8 w-[88px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="10">10 / page</SelectItem><SelectItem value="20">20 / page</SelectItem><SelectItem value="50">50 / page</SelectItem></SelectContent></Select></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={currentPage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}><ChevronLeft className="mr-1 h-4 w-4"/>Previous</Button><span className="min-w-24 text-center text-sm font-medium">Page {currentPage} of {totalPages}</span><Button variant="outline" size="sm" disabled={currentPage>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>Next<ChevronRight className="ml-1 h-4 w-4"/></Button></div></div></div></div>
}
